version: "3"

services:
  frontend:
    build:
      context: ./frontend
      target: "deps"
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
    command: /bin/sh -c "yarn dev"
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build:
      context: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
    volumes:
      - './api:/myapp'
    # environment:
    #   POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    #   POSTGRES_USER: "${POSTGRES_USER}"
    #   REDIS_URL: "${REDIS_URL}"
    ports:
      - '3010:3000'
    tty: true
    stdin_open: true
    env_file:
      - .env

  db:
    image: postgres:12.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./api/tmp/redis:/data

  sidekiq:
    build:
      context: ./api
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    volumes:
      - ./api:/myapp
      - ./api/tmp/sidekiq:/usr/local/bundle
    depends_on:
      - db
      - redis
    env_file:
      - .env
